/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as FixturesRouteImport } from './routes/fixtures'
import { Route as NewsRouteImport } from './routes/news'
import { Route as StandingsRouteImport } from './routes/standings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const FixturesRoute = FixturesRouteImport.update({
  id: '/fixtures',
  path: '/fixtures',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const StandingsRoute = StandingsRouteImport.update({
  id: '/standings',
  path: '/standings',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/favorites': typeof FavoritesRoute
  '/fixtures': typeof FixturesRoute
  '/news': typeof NewsRoute
  '/standings': typeof StandingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/favorites': typeof FavoritesRoute
  '/fixtures': typeof FixturesRoute
  '/news': typeof NewsRoute
  '/standings': typeof StandingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/favorites': typeof FavoritesRoute
  '/fixtures': typeof FixturesRoute
  '/news': typeof NewsRoute
  '/standings': typeof StandingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/favorites' | '/fixtures' | '/news' | '/standings'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/favorites' | '/fixtures' | '/news' | '/standings'
  id: '__root__' | '/' | '/favorites' | '/fixtures' | '/news' | '/standings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FavoritesRoute: typeof FavoritesRoute
  FixturesRoute: typeof FixturesRoute
  NewsRoute: typeof NewsRoute
  StandingsRoute: typeof StandingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fixtures': {
      id: '/fixtures'
      path: '/fixtures'
      fullPath: '/fixtures'
      preLoaderRoute: typeof FixturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/standings': {
      id: '/standings'
      path: '/standings'
      fullPath: '/standings'
      preLoaderRoute: typeof StandingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FavoritesRoute: FavoritesRoute,
  FixturesRoute: FixturesRoute,
  NewsRoute: NewsRoute,
  StandingsRoute: StandingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
