/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as FixturesRouteImport } from './routes/fixtures'
import { Route as NewsRouteImport } from './routes/news'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as StandingsRouteImport } from './routes/standings'
import { Route as MatchMatchIdRouteImport } from './routes/match.$matchId'
import { Route as ApiPublicPushEventsRouteImport } from './routes/api.public.push.events'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const FixturesRoute = FixturesRouteImport.update({
  id: '/fixtures',
  path: '/fixtures',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StandingsRoute = StandingsRouteImport.update({
  id: '/standings',
  path: '/standings',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchMatchIdRoute = MatchMatchIdRouteImport.update({
  id: '/match/$matchId',
  path: '/match/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPushEventsRoute = ApiPublicPushEventsRouteImport.update({
  id: '/api/public/push/events',
  path: '/api/public/push/events',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/favorites': typeof FavoritesRoute
  '/fixtures': typeof FixturesRoute
  '/news': typeof NewsRoute
  '/settings': typeof SettingsRoute
  '/standings': typeof StandingsRoute
  '/match/$matchId': typeof MatchMatchIdRoute
  '/api/public/push/events': typeof ApiPublicPushEventsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/favorites': typeof FavoritesRoute
  '/fixtures': typeof FixturesRoute
  '/news': typeof NewsRoute
  '/settings': typeof SettingsRoute
  '/standings': typeof StandingsRoute
  '/match/$matchId': typeof MatchMatchIdRoute
  '/api/public/push/events': typeof ApiPublicPushEventsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/favorites': typeof FavoritesRoute
  '/fixtures': typeof FixturesRoute
  '/news': typeof NewsRoute
  '/settings': typeof SettingsRoute
  '/standings': typeof StandingsRoute
  '/match/$matchId': typeof MatchMatchIdRoute
  '/api/public/push/events': typeof ApiPublicPushEventsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/favorites'
    | '/fixtures'
    | '/news'
    | '/settings'
    | '/standings'
    | '/match/$matchId'
    | '/api/public/push/events'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/favorites'
    | '/fixtures'
    | '/news'
    | '/settings'
    | '/standings'
    | '/match/$matchId'
    | '/api/public/push/events'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/favorites'
    | '/fixtures'
    | '/news'
    | '/settings'
    | '/standings'
    | '/match/$matchId'
    | '/api/public/push/events'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  FavoritesRoute: typeof FavoritesRoute
  FixturesRoute: typeof FixturesRoute
  NewsRoute: typeof NewsRoute
  SettingsRoute: typeof SettingsRoute
  StandingsRoute: typeof StandingsRoute
  MatchMatchIdRoute: typeof MatchMatchIdRoute
  ApiPublicPushEventsRoute: typeof ApiPublicPushEventsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fixtures': {
      id: '/fixtures'
      path: '/fixtures'
      fullPath: '/fixtures'
      preLoaderRoute: typeof FixturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/standings': {
      id: '/standings'
      path: '/standings'
      fullPath: '/standings'
      preLoaderRoute: typeof StandingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match/$matchId': {
      id: '/match/$matchId'
      path: '/match/$matchId'
      fullPath: '/match/$matchId'
      preLoaderRoute: typeof MatchMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/push/events': {
      id: '/api/public/push/events'
      path: '/api/public/push/events'
      fullPath: '/api/public/push/events'
      preLoaderRoute: typeof ApiPublicPushEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  FavoritesRoute: FavoritesRoute,
  FixturesRoute: FixturesRoute,
  NewsRoute: NewsRoute,
  SettingsRoute: SettingsRoute,
  StandingsRoute: StandingsRoute,
  MatchMatchIdRoute: MatchMatchIdRoute,
  ApiPublicPushEventsRoute: ApiPublicPushEventsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
